// Mocks generated by Mockito 5.0.16 from annotations
// in flutter_task_manager/test/repositories/user_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:flutter_task_manager/core/params/user_request.dart' as _i5;
import 'package:flutter_task_manager/features/data/auth/api/auth_api_data_source.dart'
    as _i3;
import 'package:flutter_task_manager/features/data/auth/api/model/token_response.dart'
    as _i2;
import 'package:flutter_task_manager/features/data/auth/auth_storage_impl.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeTokenResponse_0 extends _i1.Fake implements _i2.TokenResponse {}

/// A class which mocks [AuthApiDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApiDataSource extends _i1.Mock implements _i3.AuthApiDataSource {
  MockAuthApiDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.TokenResponse> createUser(_i5.UserRequest? userRequest) =>
      (super.noSuchMethod(Invocation.method(#createUser, [userRequest]),
              returnValue:
                  Future<_i2.TokenResponse>.value(_FakeTokenResponse_0()))
          as _i4.Future<_i2.TokenResponse>);
  @override
  _i4.Future<_i2.TokenResponse> authUser(_i5.UserRequest? userRequest) =>
      (super.noSuchMethod(Invocation.method(#authUser, [userRequest]),
              returnValue:
                  Future<_i2.TokenResponse>.value(_FakeTokenResponse_0()))
          as _i4.Future<_i2.TokenResponse>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [AuthStorageImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthStorageImpl extends _i1.Mock implements _i6.AuthStorageImpl {
  MockAuthStorageImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> saveToken(String? token) =>
      (super.noSuchMethod(Invocation.method(#saveToken, [token]),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  _i4.Future<String> getToken() =>
      (super.noSuchMethod(Invocation.method(#getToken, []),
          returnValue: Future<String>.value('')) as _i4.Future<String>);
  @override
  _i4.Future<void> clear() => (super.noSuchMethod(Invocation.method(#clear, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  String toString() => super.toString();
}
